Importing the Required Packages

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Reading the datas

In [2]:
books=pd.read_csv("books.csv")

In [3]:
book_tags=pd.read_csv("book_tags.csv")

In [4]:
tags=pd.read_csv("tags.csv")

Attaching tag names to each row of the book data

In [5]:
book_tags = book_tags.merge(tags, on="tag_id", how="left")

In [6]:
print(book_tags) # to have a look

        goodreads_book_id  tag_id   count           tag_name
0                       1   30574  167697            to-read
1                       1   11305   37174            fantasy
2                       1   11557   34173          favorites
3                       1    8717   12986  currently-reading
4                       1   33114   12716        young-adult
...                   ...     ...     ...                ...
999907           33288638   21303       7          neighbors
999908           33288638   17271       7    kindleunlimited
999909           33288638    1126       7       5-star-reads
999910           33288638   11478       7        fave-author
999911           33288638   27939       7           slowburn

[999912 rows x 4 columns]

In [7]:
top_tags=(book_tags.sort_values(['goodreads_book_id','count'],ascending=[True,False]).groupby('goodreads_book_id').head(5))

In [8]:
print(top_tags)

        goodreads_book_id  tag_id   count           tag_name
0                       1   30574  167697            to-read
1                       1   11305   37174            fantasy
2                       1   11557   34173          favorites
3                       1    8717   12986  currently-reading
4                       1   33114   12716        young-adult
...                   ...     ...     ...                ...
999812           33288638   30574   14116            to-read
999813           33288638    8717    1196  currently-reading
999814           33288638   26138     385            romance
999815           33288638   11557     354          favorites
999816           33288638    8055     216       contemporary

[50000 rows x 4 columns]

Explaining the merge function:
merging top_tags with books dataset on the basis of the goodreads_book_id column on the Right( left shld be written).

In [9]:
books_tags_joined=books.merge(top_tags,on="goodreads_book_id",how="left")

In [10]:
print(books_tags_joined)

       book_id  goodreads_book_id  best_book_id  work_id  books_count  \
0            1            2767052       2767052  2792775          272
1            1            2767052       2767052  2792775          272
2            1            2767052       2767052  2792775          272
3            1            2767052       2767052  2792775          272
4            1            2767052       2767052  2792775          272
...        ...                ...           ...      ...          ...
49995    10000               8914          8914    11817           31
49996    10000               8914          8914    11817           31
49997    10000               8914          8914    11817           31
49998    10000               8914          8914    11817           31
49999    10000               8914          8914    11817           31

            isbn        isbn13          authors  original_publication_year  \
0      439023483  9.780439e+12  Suzanne Collins                     2008.0
1      439023483  9.780439e+12  Suzanne Collins                     2008.0
2      439023483  9.780439e+12  Suzanne Collins                     2008.0
3      439023483  9.780439e+12  Suzanne Collins                     2008.0
4      439023483  9.780439e+12  Suzanne Collins                     2008.0
...          ...           ...              ...                        ...
49995  375700455  9.780376e+12      John Keegan                     1998.0
49996  375700455  9.780376e+12      John Keegan                     1998.0
49997  375700455  9.780376e+12      John Keegan                     1998.0
49998  375700455  9.780376e+12      John Keegan                     1998.0
49999  375700455  9.780376e+12      John Keegan                     1998.0

            original_title  ... ratings_1 ratings_2  ratings_3  ratings_4  \
0         The Hunger Games  ...     66715    127936     560092    1481305
1         The Hunger Games  ...     66715    127936     560092    1481305
2         The Hunger Games  ...     66715    127936     560092    1481305
3         The Hunger Games  ...     66715    127936     560092    1481305
4         The Hunger Games  ...     66715    127936     560092    1481305
...                    ...  ...       ...       ...        ...        ...
49995  The First World War  ...       117       345       2031       4138
49996  The First World War  ...       117       345       2031       4138
49997  The First World War  ...       117       345       2031       4138
49998  The First World War  ...       117       345       2031       4138
49999  The First World War  ...       117       345       2031       4138

       ratings_5                                          image_url  \
0        2706317  https://images.gr-assets.com/books/1447303603m...
1        2706317  https://images.gr-assets.com/books/1447303603m...
2        2706317  https://images.gr-assets.com/books/1447303603m...
3        2706317  https://images.gr-assets.com/books/1447303603m...
4        2706317  https://images.gr-assets.com/books/1447303603m...
...          ...                                                ...
49995       3069  https://images.gr-assets.com/books/1403194704m...
49996       3069  https://images.gr-assets.com/books/1403194704m...
49997       3069  https://images.gr-assets.com/books/1403194704m...
49998       3069  https://images.gr-assets.com/books/1403194704m...
49999       3069  https://images.gr-assets.com/books/1403194704m...

                                         small_image_url  tag_id  count  \
0      https://images.gr-assets.com/books/1447303603s...   11557  50755
1      https://images.gr-assets.com/books/1447303603s...    8717  35418
2      https://images.gr-assets.com/books/1447303603s...   33114  25968
3      https://images.gr-assets.com/books/1447303603s...   11743  13819
4      https://images.gr-assets.com/books/1447303603s...   10064  12985
...                                                  ...     ...    ...
49995  https://images.gr-assets.com/books/1403194704s...   30574  13510
49996  https://images.gr-assets.com/books/1403194704s...   14552    776
49997  https://images.gr-assets.com/books/1403194704s...    8717    260
49998  https://images.gr-assets.com/books/1403194704s...   21689    219
49999  https://images.gr-assets.com/books/1403194704s...   20054    114

                tag_name
0              favorites
1      currently-reading
2            young-adult
3                fiction
4              dystopian
...                  ...
49995            to-read
49996            history
49997  currently-reading
49998        non-fiction
49999   military-history

[50000 rows x 26 columns]

COMBINING ALL TAGS OF THE BOOK INTO A SINGLE STRING

books_tags_joined.groupby(['book_id','title','authors']) Groups all rows by book_id, title, and authors. So for each book, you collect all its tags together.
['tag_name'] From each group, we only care about the tag_name column (the actual text labels of tags like “fantasy”, “romance”, etc.).
.apply(lambda x: " ".join(x.dropna())) For each group (one book), take the column of tag names (x is a Series of tag names).

x.dropna() removes any missing values.

" ".join(...) combines all the tags into a single string separated by spaces. Example: ["fantasy", "magic", "adventure"] → "fantasy magic adventure" This way, each book ends up with one “document” of its tags.
.reset_index()

After grouping, the grouping keys (book_id, title, authors) become the index.

reset_index() turns them back into normal columns.

In [11]:
books_with_tags=books_tags_joined.groupby(["book_id","title","authors"])["tag_name"].apply(lambda x: " ".join(x.dropna())).reset_index()

In [12]:
print(books_with_tags)

      book_id                                              title  \
0           1            The Hunger Games (The Hunger Games, #1)
1           2  Harry Potter and the Sorcerer's Stone (Harry P...
2           3                            Twilight (Twilight, #1)
3           4                              To Kill a Mockingbird
4           5                                   The Great Gatsby
...       ...                                                ...
9995     9996                          Bayou Moon (The Edge, #2)
9996     9997  Means of Ascent (The Years of Lyndon Johnson, #2)
9997     9998                              The Mauritius Command
9998     9999  Cinderella Ate My Daughter: Dispatches from th...
9999    10000                                The First World War

                          authors  \
0                 Suzanne Collins
1     J.K. Rowling, Mary GrandPré
2                 Stephenie Meyer
3                      Harper Lee
4             F. Scott Fitzgerald
...                           ...
9995                Ilona Andrews
9996               Robert A. Caro
9997              Patrick O'Brian
9998              Peggy Orenstein
9999                  John Keegan

                                               tag_name
0     favorites currently-reading young-adult fictio...
1     to-read favorites fantasy currently-reading yo...
2             young-adult fantasy favorites vampires ya
3     classics favorites to-read classic historical-...
4        classics favorites fiction classic books-i-own
...                                                 ...
9995   to-read urban-fantasy fantasy romance paranormal
9996     to-read biography history politics non-fiction
9997  to-read historical-fiction fiction historical ...
9998  to-read non-fiction nonfiction parenting feminism
9999  to-read history currently-reading non-fiction ...

[10000 rows x 4 columns]

Building A single text field for each book ie combining the title authors and the tagnames inside a new column named features

In [13]:
books_with_tags["features"]=(books_with_tags["title"]+" "+books_with_tags["authors"]+" "+books_with_tags["tag_name"])

In [14]:
print(books_with_tags["features"])

0       The Hunger Games (The Hunger Games, #1) Suzann...
1       Harry Potter and the Sorcerer's Stone (Harry P...
2       Twilight (Twilight, #1) Stephenie Meyer young-...
3       To Kill a Mockingbird Harper Lee classics favo...
4       The Great Gatsby F. Scott Fitzgerald classics ...
                              ...
9995    Bayou Moon (The Edge, #2) Ilona Andrews to-rea...
9996    Means of Ascent (The Years of Lyndon Johnson, ...
9997    The Mauritius Command Patrick O'Brian to-read ...
9998    Cinderella Ate My Daughter: Dispatches from th...
9999    The First World War John Keegan to-read histor...
Name: features, Length: 10000, dtype: object

In [15]:
tfidf=TfidfVectorizer(stop_words="english")

In [16]:
tfidf_matrix=tfidf.fit_transform(books_with_tags['features'])

In [17]:
cosine_sim=cosine_similarity(tfidf_matrix,tfidf_matrix)

In [18]:
indices=pd.Series(books_with_tags.index,books_with_tags["title"]).drop_duplicates()

In [19]:
print(indices)

title
The Hunger Games (The Hunger Games, #1)                                                         0
Harry Potter and the Sorcerer's Stone (Harry Potter, #1)                                        1
Twilight (Twilight, #1)                                                                         2
To Kill a Mockingbird                                                                           3
The Great Gatsby                                                                                4
                                                                                             ...
Bayou Moon (The Edge, #2)                                                                    9995
Means of Ascent (The Years of Lyndon Johnson, #2)                                            9996
The Mauritius Command                                                                        9997
Cinderella Ate My Daughter: Dispatches from the Frontlines of the New Girlie-Girl Culture    9998
The First World War                                                                          9999
Length: 10000, dtype: int64

Writing the Recommendation Function

In [20]:
def recommend_books(title,n=5):
    if title not in indices:
        return"Book not found in Dataset"
    idx=indices[title]
    sim_scores=list(enumerate(cosine_sim[idx]))
    sim_scores=sorted(sim_scores,key=lambda x:x[1],reverse=True)
    sim_scores=sim_scores[1:n+1]
    book_indices=[i[0] for i in sim_scores]
    return books_with_tags[["title","authors"]].iloc[book_indices]

In [30]:
title=input("Enter the name of the book for which you want Recommendations: " )
n=int(input("Enter the number of recommendations you want: "))
recommend_books(title,n)

Enter the name of the book for which you want Recommendations:  The Fault in Our Stars
Enter the number of recommendations you want:  5

                           title                     authors
87                   Paper Towns                  John Green
73            Looking for Alaska                  John Green
274   An Abundance of Katherines                  John Green
9537          Agent to the Stars                 John Scalzi
381   Will Grayson, Will Grayson  John Green, David Levithan

In [31]:
recommend_books("Harry Potter and the Goblet of Fire (Harry Potter, #4)",7)

,title,authors
2100,"The Harry Potter Collection 1-4 (Harry Potter,...","J.K. Rowling, Mary GrandPré"
3274,"Harry Potter Boxed Set, Books 1-5 (Harry Potte...","J.K. Rowling, Mary GrandPré"
24,Harry Potter and the Deathly Hallows (Harry Po...,"J.K. Rowling, Mary GrandPré"
22,Harry Potter and the Chamber of Secrets (Harry...,"J.K. Rowling, Mary GrandPré"
1,Harry Potter and the Sorcerer's Stone (Harry P...,"J.K. Rowling, Mary GrandPré"
26,Harry Potter and the Half-Blood Prince (Harry ...,"J.K. Rowling, Mary GrandPré"
6140,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling